config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :groups
  resources :colas

   root 'home#index'

  get 'dataTourType' => 'home#dataTourType'
  get 'dataTourDays' => 'home#dataTourDays'
  get 'dataAge' => 'home#dataAge'
  get 'dataGender' => 'home#dataGender'
  get 'dataPaxType' => 'home#dataPaxType'
  get 'dataTourName' => 'home#dataTourName'
  get 'dataSeason' => 'home#dataSeason'
  get 'aboutUs' => 'home#aboutUs'

end

app/models/cola.rb
class Cola < ActiveRecord::Base
	
end

app/controllers/colas_controller.rb
class ColasController < ApplicationController
  before_action :set_cola, only: [:show, :edit, :update, :destroy]

  # GET /colas
  # GET /colas.json
  def index
    @colas = Cola.all
  end

  # GET /colas/1
  # GET /colas/1.json
  def show
  end

  # GET /colas/new
  def new
    @cola = Cola.new
  end

  # GET /colas/1/edit
  def edit
  end

  # POST /colas
  # POST /colas.json
  def create
    @cola = Cola.new(cola_params)

    respond_to do |format|
      if @cola.save
        format.html { redirect_to @cola, notice: 'Cola was successfully created.' }
        format.json { render :show, status: :created, location: @cola }
      else
        format.html { render :new }
        format.json { render json: @cola.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colas/1
  # PATCH/PUT /colas/1.json
  def update
    respond_to do |format|
      if @cola.update(cola_params)
        format.html { redirect_to @cola, notice: 'Cola was successfully updated.' }
        format.json { render :show, status: :ok, location: @cola }
      else
        format.html { render :edit }
        format.json { render json: @cola.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colas/1
  # DELETE /colas/1.json
  def destroy
    @cola.destroy
    respond_to do |format|
      format.html { redirect_to colas_url, notice: 'Cola was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cola
      @cola = Cola.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cola_params
      params[:cola]
    end
end

app/helpers/colas_helper.rb
module ColasHelper
end

app/views/colas/_form.html.erb
<%= form_for(@cola) do |f| %>
  <% if @cola.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cola.errors.count, "error") %> prohibited this cola from being saved:</h2>

      <ul>
      <% @cola.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/colas/edit.html.erb
<h1>Editing Cola</h1>

<%= render 'form' %>

<%= link_to 'Show', @cola %> |
<%= link_to 'Back', colas_path %>

app/views/colas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Colas</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @colas.each do |cola| %>
      <tr>
        <td><%= link_to 'Show', cola %></td>
        <td><%= link_to 'Edit', edit_cola_path(cola) %></td>
        <td><%= link_to 'Destroy', cola, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cola', new_cola_path %>

app/views/colas/new.html.erb
<h1>New Cola</h1>

<%= render 'form' %>

<%= link_to 'Back', colas_path %>

app/views/colas/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_cola_path(@cola) %> |
<%= link_to 'Back', colas_path %>